/**
 * Regenerates the documentation fragments that must match the code.
 *
 * Sources:
 *   - packages/create-pleyn/flags.ts          → cli-flags.md
 *   - packages/htmx-contract RULES             → rules.md
 *   - packages/htmx-contract package exports   → exports.md
 *   - both packages' package.json versions     → versions.md
 *
 * Writes under `apps/docs/src/generated/` (outside the Starlight content
 * collection). `--check` writes nothing and exits 1 when a file would change.
 */

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";

import { CLI_FLAGS } from "../../../packages/create-pleyn/flags.ts";
import { RULES } from "../../../packages/htmx-contract/rules.ts";

const ROOT = resolve(import.meta.dir, "../../..");
const OUT = resolve(import.meta.dir, "../src/generated");
const CHECK = process.argv.includes("--check");

const HEADER =
  "<!-- Generated by `bun run docs:sync`. Do not edit by hand. -->\n\n";

function table(headers: string[], rows: string[][]): string {
  const line = (cells: string[]) => `| ${cells.join(" | ")} |`;
  const sep = `| ${headers.map(() => "---").join(" | ")} |`;
  return [line(headers), sep, ...rows.map(line)].join("\n") + "\n";
}

async function packageJson(relative: string): Promise<{ name: string; version: string; exports?: Record<string, string> }> {
  const raw = await readFile(join(ROOT, relative), "utf8");
  return JSON.parse(raw) as { name: string; version: string; exports?: Record<string, string> };
}

async function writeGenerated(name: string, body: string): Promise<boolean> {
  const path = join(OUT, name);
  const next = HEADER + body;
  let previous: string | null = null;
  try {
    previous = await readFile(path, "utf8");
  } catch {
    previous = null;
  }
  if (previous === next) return false;
  if (CHECK) {
    console.error(`docs:sync: ${name} is out of date (run \`bun run docs:sync\`)`);
    return true;
  }
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, next, "utf8");
  console.log(`wrote ${name}`);
  return false;
}

const createPleyn = await packageJson("packages/create-pleyn/package.json");
const htmxContract = await packageJson("packages/htmx-contract/package.json");

const drifted: boolean[] = [];

drifted.push(
  await writeGenerated(
    "versions.md",
    [
      "Docs versioning follows **`create-pleyn`** (the product entrypoint).",
      "",
      table(
        ["Package", "Version"],
        [
          [`\`${createPleyn.name}\``, createPleyn.version],
          [`\`${htmxContract.name}\``, htmxContract.version],
        ],
      ),
    ].join("\n"),
  ),
);

drifted.push(
  await writeGenerated(
    "cli-flags.md",
    [
      "Flags accepted by `bun create pleyn <directory>`.",
      "",
      table(
        ["Flag", "What it does"],
        CLI_FLAGS.map((f) => [`\`${f.flag}\``, f.description]),
      ),
    ].join("\n"),
  ),
);

drifted.push(
  await writeGenerated(
    "rules.md",
    [
      "The rules `htmx-contract` enforces. Each has a narrative page under Rules.",
      "",
      table(
        ["Rule", "Summary"],
        RULES.map((r) => [`[\`${r.name}\`](/htmx-contract/rules/${r.name}/)`, r.summary]),
      ),
    ].join("\n"),
  ),
);

const exportEntries = Object.entries(htmxContract.exports ?? {}).sort(([a], [b]) =>
  a.localeCompare(b),
);

drifted.push(
  await writeGenerated(
    "exports.md",
    [
      `Public entry points of \`${htmxContract.name}@${htmxContract.version}\`.`,
      "",
      table(
        ["Import", "Module"],
        exportEntries.map(([key, value]) => [
          key === "." ? `\`htmx-contract\`` : `\`htmx-contract${key.slice(1)}\``,
          `\`${value}\``,
        ]),
      ),
    ].join("\n"),
  ),
);

// A JSON sidecar for pages that want structured data without parsing markdown.
const jsonPath = join(OUT, "meta.json");
const meta = {
  createPleynVersion: createPleyn.version,
  htmxContractVersion: htmxContract.version,
  flags: CLI_FLAGS,
  rules: RULES,
  exports: Object.fromEntries(exportEntries),
};
const metaBody = `${JSON.stringify(meta, null, 2)}\n`;
let metaPrevious: string | null = null;
try {
  metaPrevious = await readFile(jsonPath, "utf8");
} catch {
  metaPrevious = null;
}
if (metaPrevious !== metaBody) {
  if (CHECK) {
    console.error("docs:sync: meta.json is out of date (run `bun run docs:sync`)");
    drifted.push(true);
  } else {
    await mkdir(OUT, { recursive: true });
    await writeFile(jsonPath, metaBody, "utf8");
    console.log("wrote meta.json");
  }
}

if (CHECK && drifted.some(Boolean)) {
  process.exit(1);
}

if (!CHECK) {
  console.log("docs:sync: ok");
}
